src/accounts/urls.py
from accounts.views import AccountLoginView, AccountLogoutView, AccountPasswordChangeView, AccountRegistrationView, \
    AccountUpdateView

from django.urls import path


app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
]

src/courses/urls.py
from courses.views import CourseDeleteView, CourseListView, CourseUpdateView

from django.urls import path

app_name = "courses"

urlpatterns = [
    path('', CourseListView.as_view(), name="list"),
    path('edit/<int:course_id>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:course_id>/', CourseDeleteView.as_view(), name="delete")
]

src/groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView

app_name = "groups"


urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', GroupCreateView.as_view(), name='create'),
    path('edit/<int:group_id>', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:group_id>', GroupDeleteView.as_view(), name='delete')
]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('classrooms/', include('classrooms.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = "students"

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<int:student_id>', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:student_id>', StudentDeleteView.as_view(), name='delete')
]

src/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <title>Title</title>
</head>
<body>
<section class="header">
    <div class="container menu__container header-menu">
        <div class="menu">
            <a href="/" class="menu__logo"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
            <ul class="menu__list">
                <li class="menu__item"><a href="{% url 'groups:list' %}">Groups</a></li>
                <li class="menu__item"><a href="{% url 'teachers:list' %}">Teachers</a></li>
                <li class="menu__item"><a href="{% url 'students:list' %}">Students</a></li>
                <li class="menu__item"><a href="{% url 'courses:list' %}">Courses</a></li>
                <li class="menu__item"><a href="{% url 'classrooms:list' %}">Classrooms</a></li>
                {% if user.is_authenticated %}
                    <li class="menu__item"><a href="{% url 'accounts:profile' %}">Profile  {{ user.username }}</a></li>
                    <li class="menu__item"><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    <li><a href="{% url 'accounts:profile' %}"><img  src="{{user.profile.image.url}}" alt="" width="40px"></a></li>
                {% else %}
                <li class="menu__item"><a href="{% url 'accounts:login' %}">Sign in</a></li>
                    <li class="menu__item"><a href="{% url 'accounts:registration' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</section>
<section class="container">
    {% include 'includes/messages.html' %}
    {% block title%}
    {% endblock %}
    {% block main%}
    {% endblock %}
</section>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static%}

{% block main %}
{% endblock %}