src/courses/urls.py
from courses.views import CourseDeleteView, CourseListView, CourseUpdateView

from django.urls import path

app_name = "courses"

urlpatterns = [
    path('', CourseListView.as_view(), name="list"),
    path('edit/<int:course_id>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:course_id>/', CourseDeleteView.as_view(), name="delete")
]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('classrooms/', include('classrooms.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/models.py
import random

from django.db import models

# Create your models here.
from faker import Faker

from groups.models import Group

from teachers.models import Teacher


class Course(models.Model):
    DIFFICULTY_CHOICES = [
        (0, 'Trivial'),
        (1, 'Easy'),
        (2, 'Medium'),
        (3, 'Expert'),
        (4, 'Hardcore'),
    ]
    name = models.CharField(max_length=200)
    difficulty = models.IntegerField(
        choices=DIFFICULTY_CHOICES,
        default=0)

    group = models.OneToOneField(
        to=Group,
        on_delete=models.SET_NULL,
        null=True,
        related_name='courses'
    )

    teachers = models.ManyToManyField(
        to=Teacher,
        related_name='teachers_on_course'
    )

    @classmethod
    def generate_courses(cls, count):
        faker = Faker()
        for _ in range(count):
            course_object = cls(
                name=faker.company(),
                difficulty=random.randint(0, 4)
            )
            course_object.save()

src/courses/forms.py
from courses.models import Course

from django.forms import ModelForm, MultipleChoiceField

import django_filters

from teachers.models import Teacher


class CourseFilter(django_filters.FilterSet):
    class Meta:
        model = Course
        fields = {
            'name': ['exact', 'icontains']
        }


class CourseBaseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class CourseUpdateForm(CourseBaseForm):
    class Meta(CourseBaseForm.Meta):
        exclude = ['teachers']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        teachers = [(tc.id, tc.full_name()) for tc in Teacher.objects.all()]
        self.fields['teachers_field'] = MultipleChoiceField(choices=teachers)


class CourseCreateForm(CourseBaseForm):
    pass

src/courses/views.py
from courses.forms import CourseBaseForm, CourseFilter, CourseUpdateForm
from courses.models import Course

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, UpdateView


class CourseListView(ListView):
    model = Course
    template_name = 'courses-list.html'

    def get_filter(self):
        return CourseFilter(
            data=self.request.GET,
            queryset=self.model.objects.all()
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        return context


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = CourseUpdateForm
    template_name = 'courses-update.html'
    success_url = reverse_lazy('course:list')
    pk_url_kwarg = 'course_id'


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    form_class = CourseBaseForm
    template_name = 'courses-delete.html'
    success_url = reverse_lazy('course:list')
    pk_url_kwarg = 'course_id'

src/courses/templates/courses-delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>Delete Course?</h1>
{% endblock %}
{% block main %}
    Do you really want to delete {{course.name}}?
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'courses:list' %}">Cancel</a>
    </form>
{% endblock %}

src/courses/templates/courses-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h2>All courses</h2>
{% endblock %}
{% block main %}
<form action="" method="GET">
    {{filter.form|crispy}}
    <input type="submit" value="Search">
</form>
{% for course in filter.qs%}
    {{course.name}} <a href="{% url 'courses:update' course.id %}">EDIT</a> <a href="{% url 'courses:delete' course.id %}">DELETE</a><br>
{% endfor %}
{% endblock %}

src/courses/templates/courses-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h2>All courses</h2>
{% endblock %}
{% block main %}
<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Update">
</form>
{% for teacher in course.teachers.all %}
{{teacher.id}}</br>
{% endfor %}
{% endblock %}