src/classrooms/urls.py
from classrooms.views import ClassroomDeleteView, ClassroomListView, ClassroomUpdateView

from django.urls import path


app_name = "classrooms"

urlpatterns = [
    path('', ClassroomListView.as_view(), name="list"),
    path('edit/<int:classroom_id>/', ClassroomUpdateView.as_view(), name="update"),
    path('delete/<int:classroom_id>/', ClassroomDeleteView.as_view(), name="delete")
]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    path('classrooms/', include('classrooms.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/classrooms/models.py
import random

from django.db import models


# Create your models here.
from faker import Faker


class Classroom(models.Model):
    name = models.CharField(max_length=200, null=False)
    room_number = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.name}, {self.room_number}'

    @classmethod
    def generate_classrooms(cls, count):
        faker = Faker()
        for _ in range(count):
            classroom_object = cls(
                name=faker.company(),
                room_number=random.randint(1, 200)
            )
            classroom_object.save()

src/classrooms/forms.py
from classrooms.models import Classroom


from django.forms import ModelForm

import django_filters


class ClassroomFilter(django_filters.FilterSet):
    class Meta:
        model = Classroom
        fields = {
            'name': ['exact', 'icontains']
        }


class ClassroomBaseForm(ModelForm):
    class Meta:
        model = Classroom
        fields = '__all__'


class ClassroomUpdateForm(ClassroomBaseForm):
    pass


class ClassroomDeleteForm(ClassroomBaseForm):
    pass

src/classrooms/views.py
from classrooms.forms import ClassroomDeleteForm, ClassroomFilter, ClassroomUpdateForm
from classrooms.models import Classroom

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, UpdateView


class ClassroomListView(ListView):
    model = Classroom
    template_name = 'classrooms-list.html'

    def get_filter(self):
        return ClassroomFilter(
            data=self.request.GET,
            queryset=self.model.objects.all()
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        return context


class ClassroomUpdateView(LoginRequiredMixin, UpdateView):
    model = Classroom
    form_class = ClassroomUpdateForm
    success_url = reverse_lazy('classrooms:list')
    template_name = 'classrooms-update.html'
    pk_url_kwarg = 'classroom_id'


class ClassroomDeleteView(LoginRequiredMixin, DeleteView):
    model = Classroom
    form_class = ClassroomDeleteForm
    template_name = 'classrooms-delete.html'
    success_url = reverse_lazy('classrooms:list')
    pk_url_kwarg = 'classroom_id'

src/classrooms/templates/classrooms-delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>Delete Classrooms?</h1>
{% endblock %}
{% block main %}
    Do you really want to delete {{classroom.name}}?
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'classrooms:list' %}">Cancel</a>
    </form>
{% endblock %}

src/classrooms/templates/classrooms-list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>All Classrooms</h1>
{% endblock %}
{% block main %}
    <form action="" method="POST">
        {{filter.form|crispy}}
        <input type="submit" value="Search">
    </form>
    {% for classroom in filter.qs%}
        {{classroom.name}} {{classroom.room_number}} <a href="{% url 'classrooms:update' classroom.id %}">EDIT</a> <a href="{% url 'classrooms:delete' classroom.id %}">DELETE</a><br>
    {% endfor %}
{% endblock %}

src/classrooms/templates/classrooms-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h1>Update Classrooms</h1>
{% endblock %}
{% block main %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Update">
    </form>
{% endblock %}